services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zaq12wsX
      MYSQL_DATABASE: mockexam
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql